### ISSUE TITLE
Mobile improvements

### ISSUE THREAD

**Issue by n0rdlicht** [smartuse/platform#16]
Make the site more mobile friendly. Some issues currently present on most mobile devices. (additional map issues see: https://github.com/smartuse/smartuse-gl/issues/5)

- [x] Glider image gallery for inline images on `projects`
- [x] Fullscreen and share buttons arranged weirdly
- [x] Rendering title overlaps with map on long titles ([example](https://smartuse.ch/project/case-study-zug#anchor-1))

**Comment by loleg** [comment]
Addressed in the v0.2.0 release, thanks @n0rdlicht
